//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CA2243

[assembly: global::System.Reflection.AssemblyVersionAttribute("1.7.19.9")]
[assembly: global::System.Reflection.AssemblyFileVersionAttribute("1.7.19.9")]
[assembly: global::System.Reflection.AssemblyInformationalVersionAttribute("1.7.19+fc7c011ffb")]
#if NETSTANDARD || NETFRAMEWORK || NETCOREAPP
[global::System.CodeDom.Compiler.GeneratedCode("Nerdbank.GitVersioning.Tasks","3.9.50.28654")]
#endif
#if NET40_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NETSTANDARD2_0_OR_GREATER
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
internal static partial class ThisAssembly {
    internal const string AssemblyConfiguration = "Debug";
    internal const string AssemblyFileVersion = "1.7.19.9";
    internal const string AssemblyInformationalVersion = "1.7.19+fc7c011ffb";
    internal const string AssemblyName = "InkCanvas.PluginSdk";
    internal const string AssemblyTitle = "InkCanvas.PluginSdk";
    internal const string AssemblyVersion = "1.7.19.9";
    internal static readonly global::System.DateTime GitCommitAuthorDate = new global::System.DateTime(639211587470000000L, global::System.DateTimeKind.Utc);
    internal static readonly global::System.DateTime GitCommitDate = new global::System.DateTime(639211587470000000L, global::System.DateTimeKind.Utc);
    internal const string GitCommitId = "fc7c011ffbf6585dad4bc3e7d957b0bde382a510";
    internal const bool IsPrerelease = false;
    internal const bool IsPublicRelease = false;
    internal const string RootNamespace = "Ink_Canvas.Plugins";
}
